# Generated by Django 5.1.3 on 2025-06-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
