# Generated by Django 5.1.3 on 2025-06-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0002_alter_book_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(),
        ),
    ]
